language: ruby

script: "bundle exec rake spec"

rvm:
  - 1.9.3
  - 2.1.0

gemfile:
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_4.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true